---
- name: Linux hardening
  hosts: 192.168.101.21
  gather_facts: yes

  tasks:
    - name: Ensure firewall package is installed
      ansible.builtin.dnf:
        name: firewalld
        state: present

    - name: Ensure firewall service is up and running
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: yes
        
  handlers:
    - name: reboot_host
      ansible.builtin.reboot:
        reboot_timeout: 360
